---
name: Test/Lint
on:
  [push, workflow_dispatch]

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up python
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip python3-venv -y
          python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff
          pip install coverage

      - name: Lint files
        run: |
          source ../venv/bin/activate
          ruff check 2>&1 >> $GITHUB_STEP_SUMMARY
        working-directory: ./app

      - name: Django tests
        run: |
          source ../venv/bin/activate
          echo "Django tests:" >> $GITHUB_STEP_SUMMARY
          coverage run --source='.' --omit="*/migrations/*,app/*,manage.py" manage.py test 2>&1 >> $GITHUB_STEP_SUMMARY
          echo "<br><br>Coverage report:" >> $GITHUB_STEP_SUMMARY
          coverage report | tail -n+3 | head -n-2 | awk '{if ($4+0 < 80) print $1 " " $3 "/" $2 " " $4}' >> $GITHUB_STEP_SUMMARY
        working-directory: ./app
